### PR TITLE
Bug remove in environment.py

### PR DESCRIPTION
**Pull request by nikolay-mansas**
C:\Users\*\AppData\Local\Programs\Python\Python312\Lib\site-packages\jinja2_async_environment\environment.py:37: RuntimeWarning: coroutine 'FileSystemLoader.get_source.<locals>.uptodate' was never awaited
  if template and (not self.auto_reload or template.is_up_to_date):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### CODE REVIEW

**Comment by lesleslie** [comment]
@nikolay-mansas I thought this was a no brainer but am reverting for further review. This package was being back ported out of one of my private repos where I am using other custom loaders. It was functional but I haven't checked it in a few. I created the loaders so they'd be available but have not tested them yet. Am thrilled you're giving it a try.

Without testing, right off the bat pyright is rejecting the commit:

`/Users/les/Projects/jinja2-async-environment/jinja2_async_environment/environment.py
  /Users/les/Projects/jinja2-async-environment/jinja2_async_environment/environment.py:37:60 - error: "bool" is not awaitable
    "bool" is incompatible with protocol "Awaitable[_T_co@Awaitable]"
      "__await__" is not present (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
`

So, it's saying .is_up_to_date is not an awaitable async coroutine.

I've been sidelined working on a companion pacakge that is dependent on this and am just getting back to work on this right now. Great timing and glad you're interested. Please keep 'em coming. I am making this a priority and will address this asap.

I'll put in some initial docs and tests too here.

**Comment by lesleslie** [comment]
@nikolay-mansas If you could create another pull request, that'd be great. My excitement to merge and close this is not letting me reopen it now.

**Comment by nikolay-mansas** [comment]
> @nikolay-mansas I thought this was a no brainer but am reverting for further review. This package was being back ported out of one of my private repos where I am using other custom loaders. It was functional but I haven't checked it in a few. I created the loaders so they'd be available but have not tested them yet. Am thrilled you're giving it a try.
> 
> Without testing, right off the bat pyright is rejecting the commit:
> 
> `/Users/les/Projects/jinja2-async-environment/jinja2_async_environment/environment.py /Users/les/Projects/jinja2-async-environment/jinja2_async_environment/environment.py:37:60 - error: "bool" is not awaitable   "bool" is incompatible with protocol "Awaitable[_T_co@Awaitable]"     "__await__" is not present (reportGeneralTypeIssues) 1 error, 0 warnings, 0 informations `
> 
> So, it's saying .is_up_to_date is not an awaitable async coroutine.
> 
> I've been sidelined working on a companion pacakge that is dependent on this and am just getting back to work on this right now. Great timing and glad you're interested. Please keep 'em coming. I am making this a priority and will address this asap.
> 
> I'll put in some initial docs and tests too here.

In my project, files in the static folder are not updated without this await. I tried on windows and on my linux server, the same error everywhere. If you want, I can drop the project code in telegram or discord.

**Comment by lesleslie** [comment]
@nikolay-mansas No need to drop the project code. Looking through the Jinja environment source code, it appears that, although not async itself (there may be something the jinja async machinery does that changes this), the is_up_to_date property can return a coroutine (and the uptodate functions in the loaders are async).

If this change is working for you (and without sufficient testing myself at the moment), I'll go ahead and make the change and publish a new package.

-- les

**Pull request merged**
